name: exo_controller
description: Controlador inalámbrico para el Exo-Robot de biomecánica.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Bluetooth Classic SPP — v2 embedding, activamente mantenido
  bluetooth_classic: ^0.0.4

  # Permisos de Android en tiempo de ejecución
  permission_handler: ^11.0.0

  # Manejo de estado reactivo
  provider: ^6.1.0

  # Gráfica de líneas para roll y pitch en tiempo real
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
